First, let's read in the three CSV files again, as the previous loading cells were deleted. We'll use `pandas` to load `01_facebook_ads.csv`, `02_google_ads.csv`, and `03_tiktok_ads.csv` into separate DataFrames.

In [39]:
import pandas as pd

# Read 01_facebook_ads.csv as 'facebook'
csv_file_path_facebook = '/content/01_facebook_ads.csv'
try:
    facebook_df = pd.read_csv(csv_file_path_facebook)
    print(f"Successfully read {csv_file_path_facebook}")
except FileNotFoundError:
    print(f"Error: The file {csv_file_path_facebook} was not found.")
    facebook_df = None

# Read 02_google_ads.csv as 'google'
csv_file_path_google = '/content/02_google_ads.csv'
try:
    google_df = pd.read_csv(csv_file_path_google)
    print(f"Successfully read {csv_file_path_google}")
except FileNotFoundError:
    print(f"Error: The file {csv_file_path_google} was not found.")
    google_df = None

# Read 03_tiktok_ads.csv as 'tiktok'
csv_file_path_tiktok = '/content/03_tiktok_ads.csv'
try:
    tiktok_df = pd.read_csv(csv_file_path_tiktok)
    print(f"Successfully read {csv_file_path_tiktok}")
except FileNotFoundError:
    print(f"Error: The file {csv_file_path_tiktok} was not found.")
    tiktok_df = None

print("\nInitial DataFrames loaded.")

Successfully read /content/01_facebook_ads.csv
Successfully read /content/02_google_ads.csv
Successfully read /content/03_tiktok_ads.csv

Initial DataFrames loaded.

Now, let's normalize the column names across the three DataFrames to ensure consistency for combined analysis. We'll rename columns with similar meanings to a consistent name, such as `ad_group_id`, `ad_group_name`, `spend`, and `views`.

In [40]:
# Normalize columns for facebook_df
if facebook_df is not None:
    facebook_df = facebook_df.rename(columns={
        'ad_set_id': 'ad_group_id',
        'ad_set_name': 'ad_group_name',
        'video_views': 'views', # Align with TikTok's 'views'
        'cost': 'spend'
    })
    facebook_df['platform'] = 'Facebook'
    print("Facebook DataFrame columns normalized and 'platform' column added. First 5 rows:")
    display(facebook_df.head())

# Normalize columns for google_df
if google_df is not None:
    google_df = google_df.rename(columns={
        'cost': 'spend'
    })
    google_df['platform'] = 'Google'
    print("\nGoogle DataFrame columns normalized and 'platform' column added. First 5 rows:")
    display(google_df.head())

# Normalize columns for tiktok_df
if tiktok_df is not None:
    tiktok_df = tiktok_df.rename(columns={
        'adgroup_id': 'ad_group_id',
        'adgroup_name': 'ad_group_name'
        # 'views' is already consistent
    })
    tiktok_df['platform'] = 'TikTok'
    print("\nTikTok DataFrame columns normalized and 'platform' column added. First 5 rows:")
    display(tiktok_df.head())

Facebook DataFrame columns normalized and 'platform' column added. First 5 rows:

,date,campaign_id,campaign_name,ad_group_id,ad_group_name,impressions,clicks,spend,conversions,views,engagement_rate,reach,frequency,platform
0,2024-01-01,fb_1001,Brand_Awareness_Q1,fbset_2001,Broad_Audience_18-35,45623,892,127.5,12,8234,0.0195,38234,1.19,Facebook
1,2024-01-01,fb_1002,Conversions_Retargeting,fbset_2002,Cart_Abandoners,12456,567,215.8,34,1234,0.0455,9876,1.26,Facebook
2,2024-01-01,fb_1003,Traffic_Drive_Jan,fbset_2003,Lookalike_Purchasers,34567,1234,189.9,23,4567,0.0357,28934,1.19,Facebook
3,2024-01-02,fb_1001,Brand_Awareness_Q1,fbset_2001,Broad_Audience_18-35,42345,823,118.2,10,7890,0.0194,36789,1.15,Facebook
4,2024-01-02,fb_1002,Conversions_Retargeting,fbset_2002,Cart_Abandoners,13678,623,234.5,38,1456,0.0455,10234,1.34,Facebook

Google DataFrame columns normalized and 'platform' column added. First 5 rows:

,date,campaign_id,campaign_name,ad_group_id,ad_group_name,impressions,clicks,spend,conversions,conversion_value,ctr,avg_cpc,quality_score,search_impression_share,platform
0,2024-01-01,g_5001,Search_Brand_Terms,gad_6001,Brand_Exact,23456,1234,234.5,45,2250.0,0.0526,0.19,9,0.92,Google
1,2024-01-01,g_5002,Search_Generic_Terms,gad_6002,Product_Broad,45678,890,567.8,23,1150.0,0.0195,0.64,7,0.45,Google
2,2024-01-01,g_5003,Shopping_All_Products,gad_6003,Best_Sellers,67890,2345,423.6,67,3350.0,0.0345,0.18,8,0.67,Google
3,2024-01-02,g_5001,Search_Brand_Terms,gad_6001,Brand_Exact,24567,1289,245.6,48,2400.0,0.0525,0.19,9,0.91,Google
4,2024-01-02,g_5002,Search_Generic_Terms,gad_6002,Product_Broad,43234,823,534.2,21,1050.0,0.0190,0.65,7,0.44,Google

TikTok DataFrame columns normalized and 'platform' column added. First 5 rows:

,date,campaign_id,campaign_name,ad_group_id,ad_group_name,impressions,clicks,cost,conversions,video_views,video_watch_25,video_watch_50,video_watch_75,video_watch_100,likes,shares,comments,platform
0,2024-01-01,tt_8001,Awareness_GenZ,ttad_9001,Dance_Challenge,234567,3456,456.7,34,198234,156234,98234,67234,45234,8923,2345,567,TikTok
1,2024-01-01,tt_8002,Conversion_Focus,ttad_9002,Product_Demo,123456,2345,678.9,67,89234,67234,45234,34234,23456,4567,1234,234,TikTok
2,2024-01-01,tt_8003,Traffic_Campaign,ttad_9003,Trending_Sounds,189234,2890,345.6,23,145678,112345,89234,56789,34567,6789,1890,456,TikTok
3,2024-01-02,tt_8001,Awareness_GenZ,ttad_9001,Dance_Challenge,245678,3678,478.9,36,207345,163456,102345,70234,47234,9234,2456,589,TikTok
4,2024-01-02,tt_8002,Conversion_Focus,ttad_9002,Product_Demo,134567,2567,712.3,71,95678,71234,48234,36234,24567,4789,1345,245,TikTok

Finally, we'll combine these three normalized DataFrames into a single, comprehensive dataset. We will create a `verified_df` by concatenating `facebook_df`, `google_df`, and `tiktok_df`.

In [41]:
# Combine the three DataFrames into a single DataFrame
combined_dfs = []
if facebook_df is not None: combined_dfs.append(facebook_df)
if google_df is not None: combined_dfs.append(google_df)
if tiktok_df is not None: combined_dfs.append(tiktok_df)

if combined_dfs:
    verified_df = pd.concat(combined_dfs, ignore_index=True)
    print("Combined DataFrame created. First 5 rows:")
    display(verified_df.head())
    print("\nCombined DataFrame Info:")
    display(verified_df.info())
else:
    verified_df = pd.DataFrame()
    print("No DataFrames were available to combine.")

Combined DataFrame created. First 5 rows:

,date,campaign_id,campaign_name,ad_group_id,ad_group_name,impressions,clicks,spend,conversions,views,...,search_impression_share,cost,video_views,video_watch_25,video_watch_50,video_watch_75,video_watch_100,likes,shares,comments
0,2024-01-01,fb_1001,Brand_Awareness_Q1,fbset_2001,Broad_Audience_18-35,45623,892,127.5,12,8234.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-01-01,fb_1002,Conversions_Retargeting,fbset_2002,Cart_Abandoners,12456,567,215.8,34,1234.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-01-01,fb_1003,Traffic_Drive_Jan,fbset_2003,Lookalike_Purchasers,34567,1234,189.9,23,4567.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-01-02,fb_1001,Brand_Awareness_Q1,fbset_2001,Broad_Audience_18-35,42345,823,118.2,10,7890.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-01-02,fb_1002,Conversions_Retargeting,fbset_2002,Cart_Abandoners,13678,623,234.5,38,1456.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Combined DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 28 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     330 non-null    object
 1   campaign_id              330 non-null    object
 2   campaign_name            330 non-null    object
 3   ad_group_id              330 non-null    object
 4   ad_group_name            330 non-null    object
 5   impressions              330 non-null    int64
 6   clicks                   330 non-null    int64
 7   spend                    220 non-null    float64
 8   conversions              330 non-null    int64
 9   views                    110 non-null    float64
 10  engagement_rate          110 non-null    float64
 11  reach                    110 non-null    float64
 12  frequency                110 non-null    float64
 13  platform                 330 non-null    object
 14  conversion_value         110 non-null    float64
 15  ctr                      110 non-null    float64
 16  avg_cpc                  110 non-null    float64
 17  quality_score            110 non-null    float64
 18  search_impression_share  110 non-null    float64
 19  cost                     110 non-null    float64
 20  video_views              110 non-null    float64
 21  video_watch_25           110 non-null    float64
 22  video_watch_50           110 non-null    float64
 23  video_watch_75           110 non-null    float64
 24  video_watch_100          110 non-null    float64
 25  likes                    110 non-null    float64
 26  shares                   110 non-null    float64
 27  comments                 110 non-null    float64
dtypes: float64(19), int64(3), object(6)
memory usage: 72.3+ KB

None

Now, let's select only the relevant columns up to 'conversions' and update the 'platform' column based on the `campaign_id` prefix.

In [42]:
import numpy as np

# Select columns up to and including 'conversions'
# Note: Assuming 'platform' is kept if it exists, as it's modified next.
# If 'platform' should be dropped and re-added from scratch based on new logic,
# the column selection would need to be adjusted.
selected_columns = [
    'date', 'campaign_id', 'campaign_name', 'ad_group_id', 'ad_group_name',
    'impressions', 'clicks', 'spend', 'conversions'
]

# Ensure 'platform' column is in the selected_columns for modification if it's not already there
# In this case, 'platform' is already present due to previous steps, and we want to redefine its content
# so we re-create it.

# Create a new DataFrame with the specified columns
filtered_df = verified_df[selected_columns].copy()

# Add/Update the 'platform' column based on campaign_id
conditions = [
    filtered_df['campaign_id'].str.startswith('fb_'),
    filtered_df['campaign_id'].str.startswith('g_'),
    filtered_df['campaign_id'].str.startswith('tt_')
]
choices = ['fb', 'g', 'tt']
filtered_df['platform'] = np.select(conditions, choices, default='other')

print("DataFrame filtered to selected columns and 'platform' column updated. First 5 rows:")
display(filtered_df)

print("\nFiltered DataFrame Info:")
display(filtered_df.info())

DataFrame filtered to selected columns and 'platform' column updated. First 5 rows:

,date,campaign_id,campaign_name,ad_group_id,ad_group_name,impressions,clicks,spend,conversions,platform
0,2024-01-01,fb_1001,Brand_Awareness_Q1,fbset_2001,Broad_Audience_18-35,45623,892,127.5,12,fb
1,2024-01-01,fb_1002,Conversions_Retargeting,fbset_2002,Cart_Abandoners,12456,567,215.8,34,fb
2,2024-01-01,fb_1003,Traffic_Drive_Jan,fbset_2003,Lookalike_Purchasers,34567,1234,189.9,23,fb
3,2024-01-02,fb_1001,Brand_Awareness_Q1,fbset_2001,Broad_Audience_18-35,42345,823,118.2,10,fb
4,2024-01-02,fb_1002,Conversions_Retargeting,fbset_2002,Cart_Abandoners,13678,623,234.5,38,fb
...,...,...,...,...,...,...,...,...,...,...
325,2024-01-29,tt_8004,Influencer_Collab,ttad_9004,Creator_Partnership,423456,6890,NaN,107,tt
326,2024-01-30,tt_8001,Awareness_GenZ,ttad_9001,Dance_Challenge,295678,4345,NaN,44,tt
327,2024-01-30,tt_8002,Conversion_Focus,ttad_9002,Product_Demo,161234,3089,NaN,83,tt
328,2024-01-30,tt_8003,Traffic_Campaign,ttad_9003,Trending_Sounds,251234,3967,NaN,35,tt
329,2024-01-30,tt_8004,Influencer_Collab,ttad_9004,Creator_Partnership,434567,7012,NaN,109,tt

Filtered DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           330 non-null    object
 1   campaign_id    330 non-null    object
 2   campaign_name  330 non-null    object
 3   ad_group_id    330 non-null    object
 4   ad_group_name  330 non-null    object
 5   impressions    330 non-null    int64
 6   clicks         330 non-null    int64
 7   spend          220 non-null    float64
 8   conversions    330 non-null    int64
 9   platform       330 non-null    object
dtypes: float64(1), int64(3), object(6)
memory usage: 25.9+ KB

None

In [47]:
import plotly.io as pio
pio.renderers.default = "colab" # or "png"

In [48]:
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pandas as pd

# 1. Prepare Aggregated Data
# Aggregate daily for trends
daily_metrics = filtered_df.groupby(['date', 'platform']).agg({
    'spend': 'sum',
    'conversions': 'sum'
}).reset_index()

# Aggregate by platform for total metrics
platform_summary = filtered_df.groupby('platform').agg({
    'spend': 'sum',
    'impressions': 'sum',
    'clicks': 'sum',
    'conversions': 'sum'
}).reset_index()

# Calculate Ratios
platform_summary['CTR'] = (platform_summary['clicks'] / platform_summary['impressions']) * 100
platform_summary['CPA'] = platform_summary['spend'] / platform_summary['conversions']

# 2. Create the Dashboard
# Row 1: Totals
fig1 = make_subplots(
    rows=1, cols=4,
    subplot_titles=('Total Spend', 'Total Impressions', 'Total Clicks', 'Total Conversions')
)

metrics = ['spend', 'impressions', 'clicks', 'conversions']
for i, metric in enumerate(metrics):
    fig1.add_trace(go.Bar(x=platform_summary['platform'], y=platform_summary[metric], name=metric, marker_color='royalblue'), row=1, col=i+1)

fig1.update_layout(height=400, title_text='Aggregate Volume Metrics by Platform', showlegend=False)
fig1.show()

# Row 2: Trends
fig2 = px.line(daily_metrics, x='date', y='spend', color='platform', title='Daily Spend Trend by Platform')
fig2.update_layout(height=400)
fig2.show()

fig3 = px.line(daily_metrics, x='date', y='conversions', color='platform', title='Daily Conversions Trend by Platform')
fig3.update_layout(height=400)
fig3.show()

# Row 3: Efficiency Ratios
fig4 = make_subplots(
    rows=1, cols=2,
    subplot_titles=('CTR (clicks/impressions %)', 'CPA (cost/conversions $)')
)

fig4.add_trace(go.Bar(x=platform_summary['platform'], y=platform_summary['CTR'], name='CTR', marker_color='orange'), row=1, col=1)
fig4.add_trace(go.Bar(x=platform_summary['platform'], y=platform_summary['CPA'], name='CPA', marker_color='indianred'), row=1, col=2)

fig4.update_layout(height=400, title_text='Efficiency Metrics: CTR & CPA', showlegend=False)
fig4.show()